### ISSUE TITLE
make Systeminfo configurable

### ISSUE THREAD

**Issue by SA7BNT** [dg9vh/MMDVMHost-Websocketboard#11]
**Using x86 not Pi ARM** 

Nov 22 22:19:19 FreePBX-Dell-Keller systemd[1]: Started Python3 logtailer for MMDVMDash.
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]: /usr/lib/python3/dist-packages/gpiozero/devices.py:452: PinFactoryFallback: Falling back from rpigpio: No module named 'RPi'
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]:   'Falling back from %s: %s' % (name, str(e))))
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]: /usr/lib/python3/dist-packages/gpiozero/devices.py:452: PinFactoryFallback: Falling back from rpio: No module named 'RPIO'
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]:   'Falling back from %s: %s' % (name, str(e))))
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]: /usr/lib/python3/dist-packages/gpiozero/devices.py:452: PinFactoryFallback: Falling back from pigpio: No module named 'pigpio'
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]:   'Falling back from %s: %s' % (name, str(e))))
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]: /usr/lib/python3/dist-packages/gpiozero/devices.py:452: PinFactoryFallback: Falling back from native: unable to determine peripheral base
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]:   'Falling back from %s: %s' % (name, str(e))))
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]: Traceback (most recent call last):
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]:   File "/opt/MMDVMDash/logtailer.py", line 16, in <module>
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]:     from gpiozero import CPUTemperature
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]:   File "/usr/lib/python3/dist-packages/gpiozero/__init__.py", line 22, in <module>
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]:     from .devices import (
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]:   File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 486, in <module>
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]:     Device.pin_factory = _default_pin_factory()
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]:   File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 453, in _default_pin_factory
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]:     raise BadPinFactory('Unable to load any default pin factory!')
Nov 22 22:19:19 FreePBX-Dell-Keller python3[4597]: gpiozero.exc.BadPinFactory: Unable to load any default pin factory!
Nov 22 22:19:19 FreePBX-Dell-Keller systemd[1]: logtailer.service: Main process exited, code=exited, status=1/FAILURE
Nov 22 22:19:19 FreePBX-Dell-Keller systemd[1]: logtailer.service: Failed with result 'exit-code'.
Nov 22 22:19:20 FreePBX-Dell-Keller systemd[1]: logtailer.service: Service RestartSec=100ms expired, scheduling restart.
Nov 22 22:19:20 FreePBX-Dell-Keller systemd[1]: logtailer.service: Scheduled restart job, restart counter is at 5.
Nov 22 22:19:20 FreePBX-Dell-Keller systemd[1]: Stopped Python3 logtailer for MMDVMDash.

73 SA7BNT de Tim

**Comment by dg9vh** [comment]
Done with https://github.com/dg9vh/MMDVMHost-Websocketboard/commit/996be0b39570823c93cbf696490ea87c328e3d01 finally
