### ISSUE TITLE
Use JS/CSS Libraries Locally

### ISSUE THREAD

**Issue by myzinsky** [dg9vh/MMDVMHost-Websocketboard#16]
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/1970554/104246936-2390f800-5467-11eb-89f4-0a77ac80509a.png">

It would be nice if the used libraries would be installed locally.

**Comment by dl8tu** [comment]
as long as that is not implemented, try out this command inside your local copy of the git:

`file=./html/index.html && sed -i 's,https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css,css/bootstrap.min.css,g' $file && sed -i 's,https://code.jquery.com/jquery-3.3.1.min.js,js/jquery-3.3.1.min.js,g' $file && sed -i 's,https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js,js/popper.min.js,g' $file &&
sed -i 's,https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js,js/bootstrap.min.js,g' $file &&
sed -i 's,https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css,css/jquery.dataTables.min.css,g' $file && sed -i 's,https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js,js/jquery.dataTables.min.js,g' $file &&
HTTPPATH=./html &&
curl --fail -o ${HTTPPATH}/css/bootstrap.min.css -s https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css &&
curl --fail -o ${HTTPPATH}/js/jquery-3.3.1.min.js -s https://code.jquery.com/jquery-3.3.1.min.js &&
curl --fail -o ${HTTPPATH}/js/popper.min.js -s https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js &&
curl --fail -o ${HTTPPATH}/js/popper.min.js.map -s https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js.map &&
curl --fail -o ${HTTPPATH}/js/bootstrap.min.js -s https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js &&
curl --fail -o ${HTTPPATH}/js/bootstrap.min.js.map -s https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js.map &&
curl --fail -o ${HTTPPATH}/css/jquery.dataTables.min.css -s https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css &&
curl --fail -o ${HTTPPATH}/images/sort_both.png -s https://cdn.datatables.net/1.10.21/images/sort_both.png &&
curl --fail -o ${HTTPPATH}/images/sort_asc.png -s https://cdn.datatables.net/1.10.21/images/sort_asc.png &&
curl --fail -o ${HTTPPATH}/images/sort_desc.png -s https://cdn.datatables.net/1.10.21/images/sort_desc.png &&
curl --fail -o ${HTTPPATH}/images/sort_asc_disabled.png -s https://cdn.datatables.net/1.10.21/images/sort_asc_disabled.png &&
curl --fail -o ${HTTPPATH}/js/jquery.dataTables.min.js -s https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js
`

**Comment by dg9vh** [comment]
Checked as working solution... my question now:

Is there a legal issue including this libs into the repository?

73 Kim
