### ISSUE TITLE
showBMTGLink=1 has no effect when using DMRHost (because of a small difference in the log line format)

### ISSUE THREAD

**Issue by holzinet** [dg9vh/MMDVMHost-Websocketboard#17]
Hi Kim,

there is a difference between the log files of MMDVMHost and DMRHost resulting in a broken string and the condition _setMode(logline).startsWith("DMR"))_ could never get _true_ when using DMRHost.

See explanation and workaround below.

DMRHost:
...
M: 2021-01-29 00:32:28 DMR Slot 1, received network end of voice transmission from nnnnnnn to TG 262, 1.6 seconds
M: 2021-01-29 00:50:02 DMR Slot 2, received network voice header from nnnnnnn to TG 26298
...

MMDVMHost:
...
M: 2021-01-29 14:27:59.642 DMR Slot 1, received network end of voice transmission from nnnnnn to TG 262, 0.8 se$
M: 2021-01-29 14:28:08.746 DMR Slot 1, received network voice header from nnnnnn to TG 262
...

Workaround is easy:

change:
function getMode(logline) {
    return logline.substring(27, logline.indexOf(","));
}

in html/js/functions.js

to:
...
    return logline.substring(**23**, logline.indexOf(","));
...

Cheers,
Tino - DL8TU

**Comment by dg9vh** [comment]
Tnx for the issue, will try to find a solution that fixes it automatically...
