### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by picchiosat** [dg9vh/MMDVMHost-Websocketboard#19]
I have a multiprotocol repeaters and I see this info from Dstar mode:
![immagine](https://user-images.githubusercontent.com/8112062/107703838-8a027380-6cbc-11eb-8bd3-ff34bb96126b.png)

**Comment by dg9vh** [comment]
hi, because I have no d-star mode running here, could you send me a logfile producing such things via e-mail? See qrz.com.

**Comment by phl0** [comment]
I guess this is due to wrong RPT1/RPT2 configuration of the client's radio. Not a fault of the dashboard.

**Comment by dg9vh** [comment]
No Logfile till today... if problem persists, please react.

73
