### ISSUE TITLE
Wrong info show

### ISSUE THREAD

**Issue by picchiosat** [dg9vh/MMDVMHost-Websocketboard#28]
sometime Dashboard show this info when receive in DSTAR Mode

![immagine](https://user-images.githubusercontent.com/8112062/121750409-9e406b00-cb0c-11eb-983c-77a76727de20.png)

**Comment by dg9vh** [comment]
Tnx for the issue - will take a look at it, but actually I have some less
spare time after my hospital-time the last weeks... but it's not forgotten.
