### ISSUE TITLE
Data Table Warning Popup-Window

### ISSUE THREAD

**Issue by ernix66** [dg9vh/MMDVMHost-Websocketboard#30]
**Describe the bug**
Data Table Warning Popup-Window

like closed older issue

**Screenshots**

<img width="2105" alt="Bildschirmfoto 2021-09-25 um 08 48 24" src="https://user-images.githubusercontent.com/24961336/134761888-2fd1da68-b711-49ff-9931-703c362c4473.png">

MMDVM.log:
M: 2021-09-24 23:47:51.285 P25, network end of transmission from 0 to TG 0, 1.4 seconds, 5% packet loss
M: 2021-09-24 23:57:37.055 P25, received network transmission from KA1PIT to TG 10100
M: 2021-09-24 23:57:37.647 P25, network end of transmission from KA1PIT to TG 10100, 0.9 seconds, 0% packet loss
E: 2021-09-24 23:57:37.862 MMDVM DAC levels have overflowed
E: 2021-09-24 23:57:38.114 MMDVM DAC levels have overflowed
E: 2021-09-24 23:57:38.365 MMDVM DAC levels have overflowed
E: 2021-09-24 23:57:38.617 MMDVM DAC levels have overflowed
E: 2021-09-24 23:57:38.868 MMDVM DAC levels have overflowed
M: 2021-09-25 00:39:43.745 P25, received network transmission from 0 to TG 0
M: 2021-09-25 00:39:43.792 P25, network end of transmission from 0 to TG 0, 0.4 seconds, 38% packet loss
E: 2021-09-25 00:39:44.551 MMDVM DAC levels have overflowed
E: 2021-09-25 00:39:44.803 MMDVM DAC levels have overflowed
M: 2021-09-25 00:42:52.580 P25, received network transmission from 0 to TG 10100
M: 2021-09-25 00:42:52.626 P25, network end of transmission from 0 to TG 10100, 0.4 seconds, 0% packet loss
E: 2021-09-25 00:42:53.386 MMDVM DAC levels have overflowed
E: 2021-09-25 00:42:53.637 MMDVM DAC levels have overflowed
M: 2021-09-25 05:23:56.038 P25, network end of transmission from 0 to TG 0, 0.4 seconds, 0% packet loss

**Comment by dg9vh** [comment]
What is this 0 to TG0? Is this correct behavior or something error?

ernix66 ***@***.***> schrieb am Sa., 25. Sept. 2021, 08:55:

**Comment by ernix66** [comment]
This is a sequence of the original mmdvm Logfile. So I think it is correct behavior ...
