### ISSUE TITLE
Logging issue

### ISSUE THREAD

**Issue by f5bcb** [dg9vh/MMDVMHost-Websocketboard#33]
I find an anomaly when I query the dashboard.
For some reason the log does not display all the entries that are present in the MMDVMHost log file.

As you can see, there is some missing QSO.
Is there a "span" in terms of diration or in QSO entries ?

Here is the beginning of the log file (there is an hour difference with the one displayed by the dashboard):

M: 2021-12-25 23:04:54.745 DMR Slot 1, received network voice header from F5NHJ to TG 3022
M: 2021-12-25 23:04:54.773 DMR Slot 1, received network end of voice transmission from F5NHJ to TG 3022, 0.5 seconds, 0% packet loss, BER: 0.0%
M: 2021-12-25 23:04:57.995 DMR Slot 1, received network voice header from F5NHJ to TG 3022
M: 2021-12-25 23:05:05.777 DMR Slot 1, received network end of voice transmission from F5NHJ to TG 3022, 8.0 seconds, 0% packet loss, BER: 0.0%
M: 2021-12-25 23:24:06.841 DMR Slot 1, received network late entry from IT9ABK to TG 208
M: 2021-12-25 23:24:12.481 DMR Slot 1, network watchdog has expired, 6.2 seconds, 23% packet loss, BER: 0.0%

Here is the end of the log file as I write:

[pi@f5zjh /opt/Logs/MMDVMHost]$ sudo tail MMDVM.log
M: 2021-12-26 12:30:43.690 DMR Slot 2, received network voice header from F5JFA to TG 867
M: 2021-12-26 12:30:44.040 DMR Slot 2, received network end of voice transmission from F5JFA to TG 867, 0.1 seconds, 0% packet loss, BER: 0.0%
M: 2021-12-26 12:34:38.577 DMR Slot 1, received network voice header from FR4KM to TG 647
M: 2021-12-26 12:34:40.615 DMR Slot 1, received network end of voice transmission from FR4KM to TG 647, 2.6 seconds, 0% packet loss, BER: 8.2%
M: 2021-12-26 12:34:46.148 DMR Slot 1, received network voice header from FR4KM to TG 647
M: 2021-12-26 12:34:48.491 DMR Slot 1, received network end of voice transmission from FR4KM to TG 647, 3.0 seconds, 0% packet loss, BER: 7.7%
M: 2021-12-26 12:35:43.581 DMR Slot 2, received network voice header from F5JFA to TG 867
M: 2021-12-26 12:35:44.030 DMR Slot 2, received network end of voice transmission from F5JFA to TG 867, 0.1 seconds, 0% packet loss, BER: 0.0%
M: 2021-12-26 12:38:18.959 DMR Slot 1, received network voice header from FR4KM to TG 647
M: 2021-12-26 12:38:21.024 DMR Slot 1, received network end of voice transmission from FR4KM to TG 647, 2.6 seconds, 0% packet loss, BER: 14.5%
[pi@f5zjh /opt/Logs/MMDVMHost]$

Here is is the first QSO displayed
![image](https://user-images.githubusercontent.com/36066477/147408421-d3d4ee05-2cac-4f11-9d32-71e9bf85e500.png)

Here is the last QSO in the last page
![image](https://user-images.githubusercontent.com/36066477/147408473-ce7327d1-62b2-4e40-ba44-e6bdf84a314e.png)

**Comment by dg9vh** [comment]
There is a variable in config file defining the maximum lines of the logfile to tail.

This could be the issue.
